services:
# Node JS Express website
  node:
    image: node:18-alpine
    container_name: node-testing
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
      - ./.env:/usr/src/app/../.env
    command: ["sh", "-c", "npm install && node server.js"]

# You might like to add a depencancy like postgressql

#    depends_on:
#      - db_postgres  
#    environment:
#      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

# You might like to include postressql in you docker compose

#  db_postgres:
#    container_name: db_postgres
#    image: postgres:15-alpine
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: postgres
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data